version: '3.8'
services:
  app:
    image: my-nest-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=localhost
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DATABASE=prueba

    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=prueba
